version: "3.8"
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - ALLOWED_HOSTS=backend,localhost,srv673781.hstgr.cloud
      - CISO_ASSISTANT_URL=https://srv673781.hstgr.cloud
      - DJANGO_DEBUG=False
    volumes:
      - ./db:/code/db

  frontend:
    container_name: frontend
    environment:
      - PUBLIC_BACKEND_API_URL=http://backend:8000/api
      - PUBLIC_BACKEND_API_EXPOSED_URL=https://srv673781.hstgr.cloud/api
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend

  caddy:
    container_name: caddy
    image: caddy:2.8.4
    environment:
      - CISO_ASSISTANT_URL=https://srv673781.hstgr.cloud
    restart: unless-stopped
    ports:
      - "80:80" # Exposing port 80 for HTTP (automatic redirect to HTTPS)
      - "443:443" # Exposing port 443 for HTTPS
    volumes:
      - ./db:/data
    command: |
      sh -c 'echo "srv673781.hstgr.cloud {
        reverse_proxy /api/* backend:8000
        reverse_proxy /* frontend:3000
        tls youremail@example.com
      }" > Caddyfile && caddy run'
