version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - ALLOWED_HOSTS=srv673781.hstgr.cloud
      - CISO_ASSISTANT_URL=https://srv673781.hstgr.cloud
      - DJANGO_DEBUG=False
    volumes:
      - backend_data:/code/db

  frontend:
    container_name: frontend
    environment:
      - PUBLIC_BACKEND_API_URL=http://backend:8000/api
      - PUBLIC_BACKEND_API_EXPOSED_URL=https://srv673781.hstgr.cloud/api
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend

  caddy:
    container_name: caddy
    image: caddy:2.8.4
    environment:
      - CISO_ASSISTANT_URL=https://srv673781.hstgr.cloud
    restart: unless-stopped
    ports:
      - 8443:8443
    volumes:
      - caddy_data:/data
    command: |
      sh -c 'echo srv673781.hstgr.cloud "{
      reverse_proxy /api/* backend:8000
      reverse_proxy /* frontend:3000
      }" > /etc/caddy/Caddyfile && caddy run'

volumes:
  backend_data:
  caddy_data:
